ConnectionStrings: 
    # ProductConnection: Data Source=microservices.demo.product.db;Initial Catalog=Microservices.Demo.Product;Persist Security Info=True;User ID=sa;Password=Password1234
ServicesUrl:
    ProductApiUrl: http://Microservices.Demo.Product.API/api/products
    PolicyApiUrl:  http://Microservices.Demo.Policy.API/api/policies
ElasticApm:
    SecretToken: 
    ServerUrls: http://microservices.demo.apm-server:8200
    ServiceName: Microservices.Demo.Report.API
    Environment: production